feat: implement verification through email
Abdul-RehmanMalik/BE_App pull request #10
Opened 2023-05-22 14:14 UTC by Abdul-RehmanMalik

2023-05-22 19:39 UTC, sabhas requested changes

2023-05-22 19:39 UTC, sabhas commented on src/util/signUpmail.ts
convert all let to const

2023-05-22 19:39 UTC, sabhas commented on src/controllers/auth.ts
> +    const activationLink = `http://localhost:${process.env.PORT}/auth/activate/${user.tokens.activationToken}/${user.id}`;
don't use hard coded localhost. Use env variable

2023-05-23 05:31 UTC, Abdul-RehmanMalik commented on src/util/verifyTokensInDB.ts
> +    dbUser.tokens.activationToken===token
done

2023-05-23 05:32 UTC, Abdul-RehmanMalik commented on src/util/signUpmail.ts
done

2023-05-23 05:34 UTC, Abdul-RehmanMalik commented on src/controllers/auth.ts
> +    return "Login Successful...!";
because there is no need to show token on FE. User needs a success or failure message not a token.

2023-05-23 07:39 UTC, Abdul-RehmanMalik commented on src/models/User.ts
> +import { bool, boolean } from "joi";
removed

2023-05-23 08:04 UTC, Abdul-RehmanMalik commented on src/controllers/auth.ts
> +    const activationLink = `http://localhost:${process.env.PORT}/auth/activate/${user.tokens.activationToken}/${user.id}`;
done

2023-05-23 08:11 UTC, merged