feat: Refactor rest-api
Abdul-RehmanMalik/BE_App pull request #6
Opened 2023-05-11 14:10 UTC by Abdul-RehmanMalik

**_"Refactored Code"_**
**Files Updated:** 

- controllers/authControllers.ts 
- routes/authRoutes.ts
- routes/index.ts
- models/User.ts
- src/app.ts

**Files Added:**

- controllers/userControllers.ts 
- routes/userRoutes.ts
- util/generateAccessToken.ts
- util/Validation.ts

2023-05-11 17:21 UTC, sabhas commented on src/routes/userRoutes.ts
> +  if (error) return res.status(400).send(error.details[0].message);
move this line above const {username} = params

2023-05-11 17:40 UTC, sabhas requested changes
you need to improve file nomenclature. there's no need to specify controllers or routes in file names. Let's say a folder named controller contains some files and it will be obvious that these are controller files. So you can just name it user.ts instead of userController.ts. The same applies for every other folder.

2023-05-11 17:40 UTC, sabhas commented on src/routes/userRoutes.ts
> +  if (error) return res.status(400).send(error.details[0].message);
move this line above const {username} = params

2023-05-11 17:40 UTC, sabhas commented on src/routes/authRoutes.ts
> +    const response = await authController.createUser(body);
Although we are creating users on sign-up. it is better to have consistent names for actions. So, i would suggest to change controllers method name to signup from createuser

2023-05-11 17:40 UTC, sabhas commented on src/controllers/authController.ts
> +    const isPasswordValid = await bcrypt.compare(password, user.password);
You can perform password comparison and password hashing in the user model. You need to create static methods in the model for these actions.

2023-05-11 17:47 UTC, sabhas requested changes

2023-05-11 17:47 UTC, sabhas commented on src/models/User.ts
>    name: string;
you are extending UserPayload and all these properties exist in that interface. So, there's no need to specify these again on this UserDocument

2023-05-12 13:55 UTC, Abdul-RehmanMalik commented on src/routes/userRoutes.ts
> +  if (error) return res.status(400).send(error.details[0].message);
done

2023-05-12 13:56 UTC, Abdul-RehmanMalik commented on src/routes/authRoutes.ts
> +    const response = await authController.createUser(body);
doone

2023-05-12 13:56 UTC, Abdul-RehmanMalik commented on src/controllers/authController.ts
> +    const isPasswordValid = await bcrypt.compare(password, user.password);
done

2023-05-12 13:56 UTC, Abdul-RehmanMalik commented on src/models/User.ts
>    name: string;
done

2023-05-15 05:25 UTC, sabhas requested changes

2023-05-15 05:25 UTC, sabhas commented on package.json
> +    "start": "nodemon dist/app.js",
update this script

2023-05-15 05:25 UTC, sabhas commented on package.json
> +    "express": "^4.18.2",
express is not a dev dependency at all.

2023-05-15 05:25 UTC, sabhas commented on src/routes/users.ts
> +userRouter.get("/getuser", async (req, res) => {
there's no need to explicitly add `getuser` in api endpoint. HTTP GET `user/` already implies that you want to get a user.

2023-05-15 13:47 UTC, Abdul-RehmanMalik commented on package.json
> +    "start": "nodemon dist/app.js",
done

2023-05-15 13:47 UTC, Abdul-RehmanMalik commented on package.json
> +    "express": "^4.18.2",
done

2023-05-15 13:47 UTC, Abdul-RehmanMalik commented on src/routes/users.ts
> +userRouter.get("/getuser", async (req, res) => {
done

2023-05-17 08:58 UTC, merged